language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - cd carbon0/
  - pip install -r requirements.txt
# command to run tests
script:
  - cd carbon0/
  - python manage.py test