language: python
python:
  - "3.8"
# adding PostgreSQL
services:
  - postgresql
before_script:
  - psql -c 'create database carbon0;' -U postgres
# command to install dependencies
install:
  - cd carbon0/
  - pip install -r requirements.txt
# add the enivronment variables
env:
  - AT_GLB=assets/glb-files/Coin2.glb 
  - AT_USDZ=assets/usdz-files/Coin2.usdz 
  - DIET_GLB=assets/glb-files/carrot2.glb 
  - DIET_USDZ=assets/usdz-files/carrot2.usdz
  - UTIL_GLB=assets/glb-files/lightbulb2.glb
  - UTIL_USDZ=assets/usdz-files/lightbulb2.usdz
  - RECYCLING_GLB=assets/glb-files/Bin2.glb
  - RECYCLING_USDZ=assets/usdz-files/Bin2.usdz
  - TRANSIT_GLB=assets/glb-files/wheel2.glb
  - TRANSIT_USDZ=assets/usdz-files/wheel2.usdz
# command to run tests
script:
  - python manage.py collectstatic --noinput
  - python manage.py migrate
  - python manage.py loaddata carbon_quiz/fixtures/mission_link_data.json carbon_quiz/fixtures/question_data.json  
  - python manage.py test