version: "3.9"

services:
  django:
    build:
      context: ./carbon0
      dockerfile: DockerfilePython
    volumes:  # this allows live reload
      - ./carbon0/accounts:/usr/src/app/accounts
      - ./carbon0/api:/usr/src/app/api
      - ./carbon0/carbon0:/usr/src/app/carbon0
      - ./carbon0/carbon_quiz:/usr/src/app/carbon_quiz
      - ./carbon0/templates:/usr/src/app/templates
    expose:
      - 8000
    ports:
      - "8000:8000"
    env_file:
      - ./carbon0/.env.sample
    depends_on:
      - db
  db:
    image: postgres
    env_file:
      - ./carbon0/postgres/.env.sample
  react:
    build:
      context: ./carbon0
      dockerfile: DockerfileNode
    volumes:
      - react_static_volume:/usr/src/app/react_leaderboard
    expose:
      - 3000
    command: serve -s build -l 3000
    depends_on:
      - django

  nginx:
    restart: always
    build: ./carbon0/nginx
    volumes:
      - react_static_volume:/usr/src/app/react_leaderboard
    ports:
      - 8080:8080
    depends_on:
      - react

volumes:
  postgres_data:
  # django_static_volume:
  react_static_volume: