version: "3.9"

services:
  django:
    build:
      context: ./carbon0
      dockerfile: DockerfilePython
    volumes:
      - django_static_volume:/usr/src/app/static
    expose:
      - 8000
    ports:
      - "8000:8000"
    environment:
      - DATABASE=postgres
    env_file:
      - ./carbon0/.env
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./carbon0/postgres/.env
  react:
    build:
      context: ./carbon0
      dockerfile: DockerfileNode
    volumes:
      - react_static_volume:/usr/src/app/build/static
    expose:
      - 3000
    command: serve -s build -l 3000
    depends_on:
      - django

  nginx:
    restart: always
    build: ./carbon0/nginx
    volumes:
      - django_static_volume:/usr/src/app/django_files/static
      - react_static_volume:/usr/src/app/react_files/static
    ports:
      - 8080:8080
    depends_on:
      - react

volumes:
  postgres_data:
  django_static_volume:
  react_static_volume: