# Generated by Django 3.1.1 on 2020-09-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "completion_date",
                    models.DateTimeField(verbose_name="date mission was accomplished"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_text",
                    models.CharField(help_text="Question for the user", max_length=200),
                ),
                (
                    "question_info",
                    models.CharField(
                        help_text="Explains any vocabulary relevant to the question.",
                        max_length=200,
                    ),
                ),
                (
                    "carbon_value",
                    models.FloatField(
                        help_text="Tons of carbon that may be present in user's footprint."
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("D", "Diet"),
                            ("T", "Transit"),
                            ("R", "Recycling"),
                            ("A", "Airline-Travel"),
                            ("U", "Utilities"),
                        ],
                        help_text="The area of sustainability to which this question relates.",
                        max_length=1,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
