# Generated by Django 3.1.1 on 2020-09-08 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carbon_quiz", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question_info",
            field=models.TextField(
                help_text="Explains any vocabulary relevant to the question."
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_text",
            field=models.CharField(help_text="Question for the user", max_length=500),
        ),
    ]
