# Generated by Django 3.1.1 on 2020-09-09 00:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_quiz', '0003_question_learn_more_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='active_question',
            field=models.IntegerField(blank=True, default=0, help_text='Id of the question currently being asked.'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='carbon_value_total',
            field=models.FloatField(blank=True, default=0, help_text='Total metric tons of carbon that the user can eliminate.'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='questions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, help_text='Array of ids for the quiz questions.', null=True, size=5),
        ),
        migrations.AddField(
            model_name='quiz',
            name='slug',
            field=models.CharField(blank=True, editable=False, help_text='Unique URL path to access this quiz. Generated by the system.', max_length=500),
        ),
        migrations.AddField(
            model_name='quiz',
            name='title',
            field=models.CharField(help_text='Title of the quiz.', max_length=500, null=True, unique=True),
        ),
    ]
