# Generated by Django 3.1.1 on 2020-09-09 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carbon_quiz", "0006_auto_20200908_2109"),
    ]

    operations = [
        migrations.AddField(
            model_name="mission",
            name="learn_more",
            field=models.TextField(
                blank=True, help_text="Explains why the mission matters.", null=True
            ),
        ),
    ]
