# Generated by Django 3.1.1 on 2020-09-10 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_quiz', '0011_auto_20200909_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='completion_date',
            field=models.DateTimeField(auto_now=True, help_text='Date mission was accomplished', null=True),
        ),
    ]
