# Generated by Django 3.1.1 on 2020-09-10 20:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carbon_quiz", "0014_auto_20200910_1537"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="active_question",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="Id of the question currently being asked.",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="questions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                blank=True,
                help_text="Array of ids for the quiz questions.",
                null=True,
                size=7,
            ),
        ),
    ]
