# Generated by Django 3.1.1 on 2020-09-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carbon_quiz", "0023_remove_mission_symbol"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="achievement",
            name="zeron_image",
        ),
        migrations.AddField(
            model_name="achievement",
            name="zeron_image_url",
            field=models.CharField(
                blank=True,
                help_text="Path to the 3D model in storage.",
                max_length=200,
                null=True,
            ),
        ),
    ]
