# Generated by Django 3.1.1 on 2020-09-17 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carbon_quiz", "0025_auto_20200917_0843"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="achievement",
            name="zeron_name",
        ),
    ]
