# Generated by Django 3.1.1 on 2020-09-21 16:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_quiz', '0037_auto_20200921_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='links',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), null=True, size=3),
        ),
    ]
