# Generated by Django 3.1.1 on 2020-09-21 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_quiz', '0040_auto_20200921_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='links',
        ),
    ]
