# Generated by Django 3.1.1 on 2020-09-29 20:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carbon_quiz", "0047_auto_20200929_0849"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mission",
            name="links",
        ),
        migrations.AddField(
            model_name="mission",
            name="link_addresses",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=300, null=True),
                blank=True,
                help_text="Links that user can click to complete the mission.",
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="mission",
            name="link_descriptions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=300, null=True),
                blank=True,
                help_text="What websites the user can click to complete the mission.",
                null=True,
                size=None,
            ),
        ),
    ]
