# Generated by Django 3.1.1 on 2020-10-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_quiz', '0047_auto_20201001_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='secret_id',
            field=models.CharField(help_text='Unique id that cannot be guessed easily.', max_length=50, null=True, unique=True),
        ),
    ]
