# Generated by Django 3.1.1 on 2020-10-01 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_quiz', '0049_achievement_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='user',
        ),
    ]
