# Generated by Django 3.1.1 on 2020-10-06 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carbon_quiz", "0052_auto_20201005_1351"),
    ]

    operations = [
        migrations.AddField(
            model_name="mission",
            name="percent_carbon_sequestration",
            field=models.FloatField(
                default=0.0,
                help_text="The percent of the user's carbon footprint that completing this mission will offset.",
            ),
        ),
    ]
