# Generated by Django 3.1.1 on 2020-10-15 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carbon_quiz", "0058_auto_20201012_1444"),
        ("carbon_quiz", "0059_auto_20201014_1909"),
    ]

    operations = []
