# Generated by Django 3.1.1 on 2020-10-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carbon_quiz", "0060_auto_20201018_1100"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="improvement_response",
            field=models.IntegerField(
                choices=[(1, "Yes"), (0, "No")],
                default=0,
                help_text="Response that says the user needs to improve, with regards to this area of their carbon footprint.",
            ),
        ),
    ]
