# Generated by Django 3.1.1 on 2020-10-18 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carbon_quiz", "0061_auto_20201018_1101"),
        ("carbon_quiz", "0058_auto_20201012_1444"),
    ]

    operations = []
