# Generated by Django 3.1.1 on 2020-10-20 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carbon_quiz", "0063_merge_20201020_0949"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mission",
            name="link_addresses",
        ),
        migrations.RemoveField(
            model_name="mission",
            name="link_descriptions",
        ),
    ]
