# Generated by Django 3.1.1 on 2020-10-21 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carbon_quiz", "0065_link"),
        ("carbon_quiz", "0060_merge_20201015_1345"),
    ]

    operations = []
