# Generated by Django 3.1.1 on 2020-11-16 20:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_quiz', '0075_auto_20201116_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='open_response_answers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, help_text="User's response.", null=True), default=list, size=None),
        ),
    ]
