# Generated by Django 3.1.1 on 2020-11-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carbon_quiz", "0078_quiz_previous_carbon_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="previous_carbon_value",
            field=models.FloatField(blank=True, default=1),
        ),
    ]
