# Generated by Django 3.1.1 on 2020-11-20 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_quiz', '0079_auto_20201120_0004'),
        ('carbon_quiz', '0079_auto_20201119_1434'),
    ]

    operations = [
    ]
