# Generated by Django 3.1.1 on 2020-11-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_quiz', '0080_merge_20201120_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='previous_carbon_value',
            field=models.FloatField(blank=True, default=1, editable=False),
        ),
    ]
