# Generated by Django 3.1.1 on 2020-11-30 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_quiz', '0082_auto_20201124_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='carbon_value_total',
            field=models.FloatField(blank=True, default=1000, help_text='Total kilograms of carbon that the user can eliminate.'),
        ),
    ]
