# Generated by Django 3.1.1 on 2020-12-01 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carbon_quiz", "0083_mission_priority_level"),
        ("carbon_quiz", "0083_auto_20201130_1357"),
    ]

    operations = []
