# Generated by Django 3.1.1 on 2021-01-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carbon_quiz", "0086_auto_20201222_2029"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mission",
            name="needs_scan",
        ),
        migrations.AddField(
            model_name="mission",
            name="needs_scan",
            field=models.BooleanField(
                default=False,
                help_text="Is the mission completed by scanning a QR code.",
            ),
        ),
    ]
