# Generated by Django 3.1.1 on 2021-01-08 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_quiz', '0087_auto_20210104_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='needs_scan',
        ),
    ]
