# Generated by Django 3.1.1 on 2021-02-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carbon_quiz", "0091_auto_20210224_0927"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="learn_image",
            field=models.ImageField(
                blank=True,
                help_text="Symbolizes what user needs to work on.",
                null=True,
                upload_to="carbon_quiz/static/carbon_quiz/images",
            ),
        ),
    ]
