# Generated by Django 3.1.1 on 2021-03-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carbon_quiz", "0093_achievement_harvest_decrease"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="is_quiz_question",
            field=models.BooleanField(
                default=True, help_text="Will the question appear on a Quiz at all."
            ),
        ),
    ]
