# Generated by Django 3.1.1 on 2021-03-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carbon_quiz", "0095_auto_20210317_1459"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="is_quiz_question",
            field=models.BooleanField(
                default=True, help_text="Will the question appear on a Quiz at all."
            ),
        ),
    ]
