# Generated by Django 3.1.1 on 2021-03-17 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carbon_quiz", "0096_auto_20210317_1500"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quiz",
            name="is_quiz_question",
        ),
    ]
