# Generated by Django 3.1.1 on 2021-03-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carbon_quiz", "0097_remove_quiz_is_quiz_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="is_quiz_question",
            field=models.BooleanField(
                default=True, help_text="Will the question appear on a Quiz at all."
            ),
        ),
    ]
