# Generated by Django 3.1.1 on 2021-03-17 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("garden", "0018_auto_20210316_1745"),
        ("carbon_quiz", "0099_auto_20210317_1617"),
    ]

    operations = [
        migrations.AddField(
            model_name="mission",
            name="plant",
            field=models.OneToOneField(
                blank=True,
                help_text="Specific Plant instance to              which the mission may be related.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="garden.plant",
            ),
        ),
    ]
