# Generated by Django 3.1.1 on 2020-11-30 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_users_footprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='diet_level',
            field=models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Learning Level'), (2, 'Listening Level'), (3, 'Action Level')], default=0, help_text='Which level of Diet Missions to recommend for this player.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='offsets_level',
            field=models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Learning Level'), (2, 'Listening Level'), (3, 'Action Level')], default=0, help_text='Which level of Airlines-Utilities Missions to recommend for this player.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='recycling_level',
            field=models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Learning Level'), (2, 'Listening Level'), (3, 'Action Level')], default=0, help_text='Which level of Recycling Missions to recommend for this player.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='transit_level',
            field=models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Learning Level'), (2, 'Listening Level'), (3, 'Action Level')], default=0, help_text='Which level of Transit Missions to recommend for this player.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='utilities_level',
            field=models.IntegerField(choices=[(0, 'Not Applicable'), (1, 'Learning Level'), (2, 'Listening Level'), (3, 'Action Level')], default=0, help_text='Which level of Utilities Missions to recommend for this player.'),
        ),
    ]
