# Generated by Django 3.1.1 on 2020-12-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_auto_20201203_1216"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="diet_level",
            field=models.IntegerField(
                choices=[
                    (0, "Beginner Level"),
                    (1, "Intermediate Level"),
                    (2, "Advanced Level"),
                    (3, "Expert Level"),
                ],
                default=0,
                help_text="Which level of Diet Missions to recommend for this player.",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="offsets_level",
            field=models.IntegerField(
                choices=[
                    (0, "Beginner Level"),
                    (1, "Intermediate Level"),
                    (2, "Advanced Level"),
                    (3, "Expert Level"),
                ],
                default=0,
                help_text="Which level of Airlines-Utilities Missions to recommend for this player.",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="recycling_level",
            field=models.IntegerField(
                choices=[
                    (0, "Beginner Level"),
                    (1, "Intermediate Level"),
                    (2, "Advanced Level"),
                    (3, "Expert Level"),
                ],
                default=0,
                help_text="Which level of Recycling Missions to recommend for this player.",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="transit_level",
            field=models.IntegerField(
                choices=[
                    (0, "Beginner Level"),
                    (1, "Intermediate Level"),
                    (2, "Advanced Level"),
                    (3, "Expert Level"),
                ],
                default=0,
                help_text="Which level of Transit Missions to recommend for this player.",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="utilities_level",
            field=models.IntegerField(
                choices=[
                    (0, "Beginner Level"),
                    (1, "Intermediate Level"),
                    (2, "Advanced Level"),
                    (3, "Expert Level"),
                ],
                default=0,
                help_text="Which level of Utilities Missions to recommend for this player.",
            ),
        ),
    ]
