# Generated by Django 3.1.1 on 2020-12-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20201221_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photos_are_accurate',
            field=models.BooleanField(default=False, help_text='Whether or not the signs the player has are valid.'),
        ),
    ]
