# Generated by Django 3.1.1 on 2021-02-14 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("garden", "0002_auto_20210214_1344"),
        ("accounts", "0011_auto_20201222_1553"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="plant",
            field=models.ForeignKey(
                blank=True,
                help_text="The plants owned by this user.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="garden.plant",
            ),
        ),
    ]
