# Generated by Django 3.1.1 on 2021-02-14 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("garden", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Leaf",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_uploaded",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the leaf image was uploaded."
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="plant",
            name="leaf",
            field=models.ForeignKey(
                blank=True,
                help_text="Leaves of this plant.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="garden.leaf",
            ),
        ),
    ]
