# Generated by Django 3.1.1 on 2021-02-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("garden", "0005_auto_20210215_0944"),
    ]

    operations = [
        migrations.AddField(
            model_name="plant",
            name="created",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
