# Generated by Django 3.1.1 on 2021-03-04 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0014_auto_20210303_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machinelearning',
            name='architecture',
        ),
        migrations.RemoveField(
            model_name='machinelearning',
            name='weights',
        ),
    ]
