# Generated by Django 3.1.1 on 2021-03-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0015_auto_20210304_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='amount_harvested',
            field=models.FloatField(default=0, help_text='How much produce did you harvest this         season from your garden (in pounds)?'),
        ),
        migrations.AddField(
            model_name='plant',
            name='measuring_unit',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('lbs', 'English Pounds')], default='kg', help_text='The unit the gardener measures produce in.', max_length=3),
        ),
    ]
