# Generated by Django 3.1.1 on 2021-03-16 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("garden", "0016_auto_20210316_1233"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plant",
            old_name="amount_harvested",
            new_name="amount_harvested_total",
        ),
        migrations.RemoveField(
            model_name="plant",
            name="measuring_unit",
        ),
    ]
