# Generated by Django 3.1.1 on 2021-03-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0018_auto_20210316_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaf',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='garden/images'),
        ),
    ]
